version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - echo No build steps required for this project.
  post_build:
    commands:
      - echo Build complete.
      - echo Preparing artifacts for deployment...
artifacts:
  files:
    - public/**/*   
    - index.js
    - package.json
    - package-lock.json
  discard-paths: no     
